campusServices({"Services":[ {"title":'Food and Beverage',"inner":["Marketplace Food Court (Building D)", "35th Street Market Café (Residence)","Bits N’ Bytes (Building T)","Thunder Alley (Building A)","The Portable Feast (Building B)","First Cup Deli (Building C)","The Observatory (Building A)","The Fix Eatery ACCE Building"]},
 {"title":'Health Services ',"inner":["Ottawa Campus (C Building)", "Pembroke Campus (Room 127)"]},
 {"title":'Gym',"inner":["Algonquin Fitness Zone (Building A)"]},
 {"title":'Mail Services',"inner":["A Building"]}, 
 {"title":'Sports Therapy Clinic',"inner":["A Building"]},
 {"title":'Technology Store',"inner":["D Building"]},
 {"title":'Peer Tutoring',"inner":["E Building"]},
 {"title":'Spriritual Centre',"inner":["E Building"]},
 {"title":'Student Commons',"inner":["E Building"]},
 {"title":'Day Care Centre',"inner":["K Building"]}] }); 